title: developer-sdk-js
description: > # developer-sdk-js is a thin wrapper around the Starling Bank developer API
url: https://starlingbank.github.io
baseurl: /developer-sdk-js
git_repo: https://github.com/starlingbank/developer-sdk-js
exclude:
  - lib/gh-board
